# Molecule managed

{% if item.registry is defined %}
	FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
	FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
	{% for var, value in item.env.items() %}
		{% if value %}
			ENV {{ var }} {{ value }}
		{% endif %}
	{% endfor %}
{% endif %}

{% if item.run is defined %}
	RUN {{ item.run }}
{% endif %}

RUN if [ $(command -v apt) ]; then apt -y update && apt install -y sudo ca-certificates python3-minimal systemd systemd-sysv && apt clean; \
    elif [ $(command -v yum) ]; then yum install -y sudo python3 systemd && yum clean all; fi