---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    dockerfile: Dockerfile.j2
    privileged: true
  - name: centos
    image: docker.io/pycontribs/centos:8
    dockerfile: Dockerfile.j2
    privileged: true
provisioner:
  name: ansible
  options:
    vv: true
    D: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    # - destroy
    # - create
    # - converge
    # - verify
    # - cleanup
    # - destroy
